name: survey_kit
description: Create beautiful surveys with Flutter (inspired by iOS ResearchKit Surveys)
version: 1.0.2
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+3
  just_audio: ^0.10.4
  lottie: ^3.0.0
  universal_html: ^2.2.1
  url_launcher: ^6.1.10

dev_dependencies:
