name: survey_kit
description: Create beautiful surveys with Flutter (inspired by iOS ResearchKit Surveys)
version: 1.0.0-dev.5
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

flutter:

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  chewie: ^1.4.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.13
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.0.1
  just_audio: ^0.9.32
  lottie: ^3.0.0
  rxdart: ^0.27.7
  universal_html: ^2.2.1
  url_launcher: ^6.1.10
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3