name: Publish to pub.dev

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      id-token: write # Required for OIDC authentication
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter and Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: dart-lang/setup-dart@v1

      # Use melos-action to handle bootstrap and publishing
      - name: Publish Packages
        uses: bluefireteam/melos-action@v3
        with:
          publish: true
